# "Things info: Name: [id, cost, growth, key]",

Things: {
    "Field":       [0, -0.01, 0.0, ""],
    "Wall":        [1, -0.1, 0.0, "w"],
    "Vehicle":     [2, 10.0, -0.01, "v"],
    "Mushroom":    [3, 1.0, 0.01, "m"],
    "Cactus":      [4, -1.0, 0.01, "c"],
    "Rock":        [5, -0.5, 0.0, "r"],
    "Start":       [6, 0, 0.0, "s"],
    "Destination": [7, 10, 0.0, "d"],
    "Dot_green":    [8, 0.01, 0.0, ""],
    "Dot_red":      [9, -0.01, 0.0, ""]
}


